trigger:
  - main

stages:
  - stage: Build
    jobs:
      - job: gradleBuild
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: Gradle@4
            inputs:
              gradleWrapperFile: "gradlew"
              tasks: "build"
              publishJUnitResults: true
              testResultsFiles: "**/TEST-*.xml"
              javaHomeOption: "JDKVersion"
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: false
              spotBugsAnalysis: false

          - task: CopyFiles@2
            displayName: "Copy Files to artifact staging directory"
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)"
              Contents: "**/build/libs/*.jar"
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: webapp
